insert into genres(id,name) values(28,'Action');
insert into genres(id,name) values(12,'Adventure');
insert into genres(id,name) values(16,'Animation');
insert into genres(id,name) values(35,'Comedy');
insert into genres(id,name) values(80,'Crime');
insert into genres(id,name) values(99,'Documentary');
insert into genres(id,name) values(18,'Drama');
insert into genres(id,name) values(10751,'Family');
insert into genres(id,name) values(14,'Fantasy');
insert into genres(id,name) values(36,'History');
insert into genres(id,name) values(27,'Horror');
insert into genres(id,name) values(10402,'Music');
insert into genres(id,name) values(9648,'Mystery');
insert into genres(id,name) values(10749,'Romance');
insert into genres(id,name) values(878,'Science Fiction');
insert into genres(id,name) values(10770,'TV Movie');
insert into genres(id,name) values(53,'Thriller');
insert into genres(id,name) values(10752,'War');
insert into genres(id,name) values(37,'Western');
