-- Generated by the database client.
CREATE TABLE transactions(
    id SERIAL NOT NULL,
    code_ticket text,
    user_id integer,
    schedule_id integer,
    payment_id integer,
    paid_at timestamp without time zone,
    total_price double precision,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    rating double precision,
    PRIMARY KEY(id),
    CONSTRAINT transactions_schedule_id_fkey FOREIGN key(schedule_id) REFERENCES schedules(id),
    CONSTRAINT transactions_payment_id_fkey FOREIGN key(payment_id) REFERENCES payments(id),
    CONSTRAINT transactions_users_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);