-- Generated by the database client.
CREATE TABLE seats(
    id SERIAL NOT NULL,
    code varchar(3),
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX seat_code_unique_cons ON public.seats USING btree (code);