-- Generated by the database client.
CREATE TABLE movie_genres(
    movie_id integer,
    genre_id integer,
    CONSTRAINT genres_movies_movie_id_fkey FOREIGN key(movie_id) REFERENCES movies(id),
    CONSTRAINT genres_movies_genre_id_fkey FOREIGN key(genre_id) REFERENCES genres(id)
);