-- Generated by the database client.
CREATE TABLE schedules(
    id SERIAL NOT NULL,
    schedule timestamp without time zone,
    movie_id integer,
    city_id integer,
    cinema_id integer,
    PRIMARY KEY(id),
    CONSTRAINT schedules_movie_id_fkey FOREIGN key(movie_id) REFERENCES movies(id),
    CONSTRAINT schedules_city_id_fkey FOREIGN key(city_id) REFERENCES cities(id),
    CONSTRAINT schedules_cinema_id_fkey FOREIGN key(cinema_id) REFERENCES cinemas(id)
);