-- Generated by the database client.
CREATE TABLE profiles(
    user_id integer,
    first_name varchar(25) DEFAULT 'user'::character varying,
    last_name varchar(25) DEFAULT 'user'::character varying,
    avatar_path text,
    point integer DEFAULT 0,
    phone_number varchar(25),
    gender gender,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone,
    CONSTRAINT profiles_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);