-- Generated by the database client.
CREATE TABLE movie_actors(
    movie_id integer,
    actor_id integer,
    CONSTRAINT actors_movies_actor_id_fkey FOREIGN key(actor_id) REFERENCES actors(id),
    CONSTRAINT actors_movies_movie_id_fkey FOREIGN key(movie_id) REFERENCES movies(id)
);