-- Generated by the database client.
CREATE TABLE order_seats(
    transaction_id integer,
    seat_id integer,
    CONSTRAINT order_seat_transaction_id_fkey FOREIGN key(transaction_id) REFERENCES transactions(id),
    CONSTRAINT order_seat_seat_id_fkey FOREIGN key(seat_id) REFERENCES seats(id)
);