-- Generated by the database client.
CREATE TABLE movies(
    id SERIAL NOT NULL,
    poster_path varchar(100),
    backdrop_path varchar(100),
    title varchar(70),
    overview text,
    release_date date,
    duration integer,
    director_id integer,
    deleted_at timestamp without time zone,
    PRIMARY KEY(id),
    CONSTRAINT movies_director_id_fkey FOREIGN key(director_id) REFERENCES directors(id)
);