-- Generated by the database client.
CREATE TABLE users(
    id SERIAL NOT NULL,
    email varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    role user_role DEFAULT 'user'::user_role,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_email_unique_cons ON public.users USING btree (email);